export const env = {
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  quotesUploadsBucket: process.env.QUOTES_UPLOADS_BUCKET ?? "quotes-assets",
  stripePricePerHourCents: Number(process.env.STRIPE_PRICE_PER_HOUR_CENTS ?? "5000"),
  stripeCurrency: process.env.STRIPE_CURRENCY ?? "usd",
  edgeFunctionSecret: process.env.EDGE_FUNCTION_SECRET ?? "",
  edgeFunctionUrl: process.env.EDGE_FUNCTION_URL ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: process.env.SMTP_PORT ?? "2587",
  smtpUser: process.env.SMTP_USERNAME ?? "",
  smtpPass: process.env.SMTP_PASSWORD ?? "",
  smtpFrom: process.env.SMTP_FROM ?? "",
};
